=== Ionate-Inc/XpaDemo/Export/CustomersList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:Magic xpa.printdata" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Print_data" type="urn:Print_dataType" xmlns:urn="urn:Magic xpa.printdata"/>
  <xs:complexType name="RecordType">
    <xs:sequence>
      <xs:element type="xs:string" name="Ndx"/>
      <xs:element type="xs:string" name="CustomerID"/>
      <xs:element type="xs:string" name="CompanyName"/>
      <xs:element type="xs:string" name="ContactName"/>
      <xs:element type="xs:string" name="ContactTitle"/>
      <xs:element type="xs:string" name="Address"/>
      <xs:element type="xs:string" name="City"/>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="PostalCode"/>
      <xs:element type="xs:string" name="Country"/>
      <xs:element type="xs:string" name="Phone"/>
      <xs:element type="xs:string" name="Fax"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Print_dataType">
    <xs:sequence>
      <xs:element type="urn:RecordType" name="Record" maxOccurs="unbounded" minOccurs="0" xmlns:urn="urn:Magic xpa.printdata"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Ionate-Inc/XpaDemo/Export/old/CustomersList.xml
<?xml version="1.0" encoding="UTF-8"?>
<Print_data xmlns="urn:Magic xpa.printdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:Magic xpa.printdata C:\Magic\projects\XpaDemo\\Export\CustomersList.xsd">
<Record><Ndx>0</Ndx><CustomerID>AROUT</CustomerID><CompanyName>Around Table</CompanyName><ContactName>Thomas Hardy</ContactName><ContactTitle>Sales Representative</ContactTitle><Address>120 Hanover Sq.</Address><City>London</City><Region></Region><PostalCode>WA1 1DP</PostalCode><Country>UK</Country><Phone>(171) 555-7788</Phone><Fax>(171) 555-6750</Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>BSBEV</CustomerID><CompanyName>B&apos;s Beverages</CompanyName><ContactName>Victoria Ashworth</ContactName><ContactTitle>Sales Representative</ContactTitle><Address>Fauntleroy Circus</Address><City>London</City><Region></Region><PostalCode>EC2 5NT</PostalCode><Country>UK</Country><Phone>(171) 555-1212</Phone><Fax></Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>CONSH</CustomerID><CompanyName>Consolidated Holdings</CompanyName><ContactName>Elizabeth Brown</ContactName><ContactTitle>Sales Representative</ContactTitle><Address>Berkeley Gardens 12  Brewery</Address><City>London</City><Region></Region><PostalCode>WX1 6LT</PostalCode><Country>UK</Country><Phone>(171) 555-2282</Phone><Fax>(171) 555-9199</Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>EASTC</CustomerID><CompanyName>Eastern Connection</CompanyName><ContactName>Ann Devon</ContactName><ContactTitle>Sales Agent</ContactTitle><Address>35 King George</Address><City>London</City><Region></Region><PostalCode>WX3 6FW</PostalCode><Country>UK</Country><Phone>(171) 555-0297</Phone><Fax>(171) 555-3373</Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>ISLAT</CustomerID><CompanyName>Island Trading</CompanyName><ContactName>Helen Bennett</ContactName><ContactTitle>Marketing Manager</ContactTitle><Address>Garden House Crowther Way</Address><City>Cowes</City><Region>Isle of Wight</Region><PostalCode>PO31 7PJ</PostalCode><Country>UK</Country><Phone>(198) 555-8888</Phone><Fax></Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>NORTS</CustomerID><CompanyName>North/South</CompanyName><ContactName>Simon Crowther</ContactName><ContactTitle>Sales Associate</ContactTitle><Address>South House 300 Queensbridge</Address><City>London</City><Region></Region><PostalCode>SW7 1RZ</PostalCode><Country>UK</Country><Phone>(171) 555-7733</Phone><Fax>(171) 555-2530</Fax></Record>
<Record><Ndx>0</Ndx><CustomerID>SEVES</CustomerID><CompanyName>Seven Seas Imports</CompanyName><ContactName>Hari Kumar</ContactName><ContactTitle>Sales Manager</ContactTitle><Address>90 Wadhurst Rd.</Address><City>London</City><Region></Region><PostalCode>OX15 4NB</PostalCode><Country>UK</Country><Phone>(171) 555-1717</Phone><Fax>(171) 555-5646</Fax></Record>
</Print_data>
